### ISSUE TITLE
extension is not working please don't try this

### ISSUE THREAD

**Issue by overtatechdeveloper** [EaDesgin/Magento2-City-Dropdown#57]
1 exception(s):
Exception #0 (OutOfRangeException): Specified invalid parent id (Eadesigndev_Pdfgenerator::templates)

Exception #0 (OutOfRangeException): Specified invalid parent id (Eadesigndev_Pdfgenerator::templates)
#0 /home/samathg6/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\Model\Menu\Builder->getResult(Object(Magento\Backend\Model\Menu))
#1 /home/samathg6/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Backend\Model\Menu\Builder\Interceptor->___callParent('getResult', Array)
#2 /home/samathg6/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Backend\Model\Menu\Builder\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Backend\Model\Menu))

**Comment by mariusik88** [comment]
Si eu primesc aceasta eroare.

**Comment by logiqdesign18** [comment]
@mariusik88  and @overtatechdeveloper upload Eadesigndev_Core from repository before install City_Dropdown and dont change anything.
