### ISSUE TITLE
When Editing Customer information it's throwing an error

### ISSUE THREAD

**Issue by shravan148** [EaDesgin/Magento2-City-Dropdown#60]
![romcity](https://user-images.githubusercontent.com/46593382/55072415-0d0e8680-50b1-11e9-96af-57371eaefd8e.PNG)

**Comment by shravan148** [comment]
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Eadesigndev\RomCity\Block\Checkout\CityUpdater::citiesJson

Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Eadesigndev\RomCity\Block\Checkout\CityUpdater::citiesJson
#0 /chroot/home/adde9e18/saksooka.com/html/app/code/Eadesigndev/RomCity/view/adminhtml/templates/city-admin.phtml(7): Magento\Framework\DataObject->__call('citiesJson', Array)
#1 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/chroot/home/ad...')
#2 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Eadesigndev\RomCity\Block\Checkout\CityUpdater), '/chroot/home/ad...', Array)
#3 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/chroot/home/ad...')
#4 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#5 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#6 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('city-admin')
#7 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('city-admin')
#8 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('city-admin')
#9 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('city-admin', true)
#10 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('city-admin')
#11 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content')
#12 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#13 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#14 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#15 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#16 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.col')
#17 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#18 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#19 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#20 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#21 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#22 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#23 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#24 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#25 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#26 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#27 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#28 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#29 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#30 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#31 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.content')
#32 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#33 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#34 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#35 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#36 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#37 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#38 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#39 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#40 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#41 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('backend.page')
#42 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#43 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#44 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#45 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#46 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root')
#47 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#48 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#49 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#50 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#51 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#52 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#53 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#54 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#55 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#56 /chroot/home/adde9e18/saksooka.com/html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#57 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#58 /chroot/home/adde9e18/saksooka.com/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#59 {main}

**Comment by shravan148** [comment]
Can anybody help us on this.. our site is live and we want to fix it ASAP

**Comment by shravan148** [comment]
Why it is invalid??

**Comment by AboElnoor** [comment]
It shouldn't be invalid I think. but try the solution in the following issue:

https://github.com/EaDesgin/Magento2-City-Dropdown/issues/66
