### ISSUE TITLE
I haven't found any installation guid for this plugin. 

### ISSUE THREAD

**Issue by BathiyaD** [EaDesgin/Magento2-City-Dropdown#61]
I really need to know. what are the steps that i need to follow to insatall this plugin. and also i need what is the file name and path that i need to extract the extension,

**Comment by AboElnoor** [comment]
I vote up for this issue, readme file is not clear about installation and also using the extension

**Comment by fdo36** [comment]
I vote up for this issue, readme file is not clear about installation and also using the extension
